<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.dfs</groupId>
		<artifactId>dfs-parent</artifactId>
		<version>0.1.0-SNAPSHOT</version>
	</parent>
	<artifactId>datanode</artifactId>
	<name>DistributedFS DataNode</name>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>com.dfs</groupId>
			<artifactId>shared</artifactId>
			<version>0.1.0-SNAPSHOT</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
                    <!-- 👇 Add this line: replace with your actual main class -->
                    <mainClass>com.dfs.datanode.DataNodeApplication</mainClass>
                </configuration>
			</plugin>
		</plugins>
	</build>
</project>


